spring:
  config:
    import: aws-parameterstore:/eatngo/
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
