server:
  port: 8081

spring:
  config:
    import:
      - classpath:auth-application.yml
      - classpath:infra-application.yml
  application:
    name: eatngo-store-owner-api
  jpa:
    open-in-view: false
    # Hibernate가 PostgreSQL 방언을 사용하도록 설정
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: eatngolocal
      repositories:
          enabled: false

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: eatngo-app

datastore:
  mongodb:
    uri: mongodb://localhost:27017/eatngo
    database: eatngo
    username: eatngo-owner
    password: eatngolocal

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

swagger:
  title: "EatNGo 점주 API"
  description: "EatNGo 서비스의 점주용 API 문서"
  version: "v1.0.0"

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
