spring:
  profiles:
    active: local
  config:
    import: aws-parameterstore:/eatngo/
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
datastore:
  mongodb:
    uri: localhost:27017/APP
    database: APP
    username: eatngo-owner
    password: eatngolocal
