spring:
  profiles:
      active: local
  config:
    import: aws-parameterstore:/eatngo/
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
  datasource:
    url: localhost:5432/eatngo
    username: eatngo_user
    password: eatngolocal
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect